### ISSUE TITLE
Pending update

### ISSUE THREAD

**Issue by WilsonJr01** [lightninglabs/lightning-terminal#488] opened 2023-02-15 00:51 UTC
I have a problem with lightning-terminal. I updated my pool account, but the txid never made it to the mempool and now the account is stuck in pending update.
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

Umbrel

**Comment by ellemouton** [comment] 2023-02-15 07:01
Hi @WilsonJr01! Thanks for reporting, I will pass this issue on to the pool team 👍

**Comment by positiveblue** [comment] 2023-02-15 08:22
I think I know what is going on here. Can you share your account_id?

It’s possible that your client got out of sync when you updated your account (deposit/withdraw funds) while it was participating in a batch. Did you sold/bought any channel lately?


If this is what happened you will have to go through the account recovery process. Your account will be in synced again and you will be able to use your funds as usual but the old, non matched, orders will be canceled and the information about out leases too.

**Comment by WilsonJr01** [comment] 2023-02-15 21:34
where can I see my account_id? my trader key is 02be88105cf997b06b0cb6a5569b835bc0d8cd0c689be15648c7d6b0bfd955bb30

I already try to do the recovery process, but it didn't worked

**Comment by positiveblue** [comment] 2023-02-16 11:41
In this case the client did not get out of sync with the server by interacting with his account while participating in a batch. 

The user deposited new funds in his account calling the [DepositAccount](https://github.com/lightninglabs/pool/blob/master/rpcserver.go#L710) rpc method. A new `AccountDiff` was created with a tx that had three inputs and two outputs
- in: current account outpoint
- in: utxo from lnd wallet
- in: utxo from lnd wallet
- out: new account output
- out: change


The account diff has not been applied to the account because is waiting for confirmations. However, that tx was never broadcasted to the network. The lnd node does not see it in pending txs and the two inputs that the lnd node manages are not seen as "spent".

In the lnd logs we can see that a subscription was created for this tx but was canceled few minutes later `NTFN: Canceling confirmation notification:`


Umbrel does not store the container logs for more than one day, so we do not have them for pool.

The account is currently unusable because of it's `Pending Updating` state.

**Comment by cinartec** [comment] 2023-04-15 13:42
Is there a fix for this bug?

**Comment by guggero** [comment] 2023-04-17 07:59
There is no fix yet, but we are working on one. If you are affected, you can tell us your account key (=trader key) and we can reset it on the server side. Then you can use the account recovery to sync your local account state: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery

**Comment by cinartec** [comment] 2023-04-20 05:39
Greetings,
Here is my Trader Key:  03c3b96f13fb06c103f9e44952b62e933d0104e58eaeb492b946e4a8392074b8af
thank you so much.

> There is no fix yet, but we are working on one. If you are affected, you can tell us your account key (=trader key) and we can reset it on the server side. Then you can use the account recovery to sync your local account state: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery

**Comment by guggero** [comment] 2023-04-20 07:44
I have removed the pending state on the server side, you can now proceed with the account recovery.

**Comment by guggero** [comment] 2023-04-21 07:50
Those funds should be back in your lnd wallet. If not, try a restart of lnd.

**Comment by cinartec** [comment] 2023-04-21 08:18
restarting my lnd did not work.  I am not sure where the fund went now?

**Comment by guggero** [comment] 2023-04-21 08:45
Are you sure you didn't use the funds for something else in the meantime? When I reset the state I saw that the wallet input was spent in another transaction in the meantime. Maybe you opened a channel or sent funds and that's where they are now?

**Comment by cinartec** [comment] 2023-04-22 06:04
> Are you sure you didn't use the funds for something else in the meantime? When I reset the state I saw that the wallet input was spent in another transaction in the meantime. Maybe you opened a channel or sent funds and that's where they are now?

thanks Guggero,  I do sincerely recalled that my balance was 11,000,000 SAT while the ACCOUNT STATUS stuck in PENDING UPDATE stage.  
After I ran and executed account recover on container "lightninglabs/lightning-terminal:v0.8.6-alpha."  my account is down to 5,000,000 SAT.   So I am not sure where is the 6,000,000 went?  
I might have ran the recovery command on the wrong container?

**Comment by guggero** [comment] 2023-04-22 13:56
Yes, the pending transaction attempted to add 6M sats to the account. But because that deposit transaction never confirmed because the funds were spent by the `lnd` wallet in the meantime, the funds should be accounted for somewhere in `lnd` (either in a channel you opened or another transaction your node made). So you just need to add the funds to the Pool account again.

**Comment by levmi** [comment] 2023-05-17 19:21
Closing due to inactivity, let us know if you need more help.

**Closed by levmi** 2023-05-17 19:21 UTC
Labels: bug
