### ISSUE TITLE
Forwards are not displayed since Sep. 24th 2023

### ISSUE THREAD

**Issue by MButcho** [lightninglabs/lightning-terminal#646] opened 2023-09-30 11:42 UTC
Dashboard is not showing forwards since Sep. 24th 2023, no error msg is present

Showing forwards with correct fee calculation

No forwards displayed since Sep. 24th 2023
**1D**
![image](https://github.com/lightninglabs/lightning-terminal/assets/41790777/983639fa-7744-402c-9f02-1586b712e95e)
**1W**
![image](https://github.com/lightninglabs/lightning-terminal/assets/41790777/10bef7bb-1049-417e-abf6-b38a3f60426b)

This happens every time on various devices with various sessions

lnd-mode=remote

Website and unpacked binaries (lits 0.10.5-alpha)

Intel NUC, 8 GB RAM, 2 TB SSD

Ubuntu 22.04 and lnd 0.16.4

2023-09-30 13:33:17.335 [WRN] GRPC: [transport] transport: http2Server.HandleStreams failed to read frame: error decrypting payload: error reading from go-back-n: cannot receive, gbn exited
2023-09-30 13:33:26.676 [INF] LOOPD: Monitor request received
2023-09-30 13:33:29.460 [INF] LOOPD: Get LSAT tokens request received

**Comment by MButcho** [comment] 2023-09-30 18:00
Started to work:
![image](https://github.com/lightninglabs/lightning-terminal/assets/41790777/02644b07-bb69-4013-a27c-4205a8e45b9f)

**Comment by MButcho** [comment] 2023-10-02 11:32
And not working again:
![image](https://github.com/lightninglabs/lightning-terminal/assets/41790777/f9a3bbaa-e6e0-444f-af02-549e88463762)

**Comment by jamaljsr** [comment] 2023-10-02 20:59
Ok, I have confirmed that there is an issue here. I'll investigate the cause and get a fix up as soon as possible. Thanks for the bug report 👍

**Comment by levmi** [comment] 2023-10-10 23:18
Should be fixed with the latest release. Let us know if not!

**Closed by levmi** 2023-10-10 23:18 UTC
Labels: bug
