### ISSUE TITLE
It gives me a "wrong password" after restarting Umbrel.

### ISSUE THREAD

**Issue by diegokolling** [lightninglabs/lightning-terminal#372] opened 2022-05-24 00:26 UTC
After submitting an ask order this last saturday, of around 7MM for 2 weeks, 17% APR, I started seeing error messages on Interface of Lightning Terminal app on Umbrel, updated to the last version (LND 14.2 and Umbrel 0.18).

It was saying that it couldnt fetch a lot of things: My nodes Tier, my orders, and so on...

So I restarted Umbrel and it got worse: Lightning Terminal is the only app not loading properly.

It first give me messages of "error_connection_refused" before getting connected. But when it does, it does not accept my password anymore, the same as always...

All other apps working properly...

So I dont have a GUI interface for my Pool funds anymore.

1) Whats happening to Lightning Terminal app? Why it started giving me error messages and then apparently broke even more, after restarting Umbrel?

2) In the meanwhile, how do I check through command line my funds and/or have my funds back and Pool account closed? Can you guys be specific, since Im not that used to command line? 

A little bit of more context:

I first opened my Pool account 10 days ago. I submitted various orders. For a week it was all working properly. I could access Terminal and check on them.

Since none of them got accepted, I withdraw the orders and remade a one, bigger ask proposal with all my funds (last saturday). That is when things blew up.

Thank you guys for your attention.

**Comment by jamaljsr** [comment] 2022-05-24 15:00
> 1. Whats happening to Lightning Terminal app? Why it started giving me error messages and then apparently broke even more, after restarting Umbrel?

This is difficult to answer without more information.

> 2. In the meanwhile, how do I check through command line my funds and/or have my funds back and Pool account closed? Can you guys be specific, since Im not that used to command line?
 
Here are steps you can follow to close your account and return the funds to your LND wallet.
1. SSH into the Umbrel node. The password is the same one you use to login to the Umbrel website
   ```
   ssh umbrel@umbrel.local
   ```
   > This command works on Mac & Linux. If you are using a Windows computer, you'll need to use an app like [PuTTY](https://www.putty.org/) to SSH into the Umbrel node.
2. Once logged in, your terminal prompt should say `umbrel@umbrel:~ $`
3. Run `bash` inside the `lightning-terminal` docker container
   ```
   docker exec -it lightning-terminal_web_1 bash
   ```
4. When inside the container, your terminal prompt should say `bash-5.1 $`
5. Run the `pool` CLI command to list your accounts
   ```
   pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts list
   ```
6. It will output your account information, such as
   ```
   {
	"accounts": [
		{
			"trader_key": "026b7447973b79e8eaf79258c104b716a8107eedeeb25e484616daf001cf24bba3",
			"outpoint": "5b09744a8a4ab8e31eabd1e14ce7de9c434dedf13ab9fe6b27bd2ab807276f04:0",
			"value": 5381514,
			"available_balance": 5381514,
			"expiration_height": 1906780,
			"state": "EXPIRED",
			"latest_txid": "5b09744a8a4ab8e31eabd1e14ce7de9c434dedf13ab9fe6b27bd2ab807276f04"
		}
	]
   }
   ```
7. The `trader_key` value is what you'll need for the next command.
8. Run the `pool` CLI command to close this account
    ```
    pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts close <trader_key> <sat_per_vbyte>
    ```
    Replace `<trader_key>` with the value from step 6 and replace the `<sat_per_vbyte>` with the fee rate you'd like to use.

To quit the SSH session, just enter the `exit` command twice.

**Comment by diegokolling** [comment] 2022-05-24 19:28
Nice, Jamal! Thank you one more time.

On step 3, I got the error message: Error response from daemon: Container
919a62889fe31efa91ce78529e4411231d36c8fd6b9815d3110bb9201c971b2a is
restarting, wait until the container is running.

One question: does it solve to reinstall Lightning Terminal app on my
Umbrel? Or it will erase the data and not help me anyway?

ps: I found you on Slack if you prefer a more agile way of sorting through
out of this!

*Diego Kolling*


Em ter., 24 de mai. de 2022 às 12:00, Jamal James ***@***.***>
escreveu:

**Comment by diegokolling** [comment] 2022-05-24 19:41
Actually, this might be of some help: the logs from Umbrel, specially from
lightning terminal app.

lightning-terminal

web_1  | 2022-05-24 19:37:45.669 [INF] LNDC: Waiting for lnd to be fully
synced to its chain backend, this might take a while
web_1  | 2022-05-24 19:37:45.811 [INF] LNDC: lnd is now fully synced to its
chain backend
web_1  | 2022-05-24 19:37:46.058 [INF] LOOPD: Swap server address:
swap.lightning.today:11010
web_1  | 2022-05-24 19:37:46.062 [INF] STORE: Checking for schema update:
latest_version=4, db_version=4
web_1  | 2022-05-24 19:37:46.331 [INF] POOL: Version: 0.5.6-alpha
commit=v0.5.6-alpha-lnd-14
web_1  | 2022-05-24 19:37:46.332 [INF] LOOPD: Waiting for updates
web_1  | 2022-05-24 19:37:46.332 [INF] LOOPD: Starting swap client
web_1  | 2022-05-24 19:37:46.333 [INF] LOOP: Connected to lnd node 'dbnk'
with pubkey
03d76e15709c57225560af75576b71c4d72dbac0dffaaba5ab8cc94e17ff8e708f (version
v0.14.2-beta, build tags
'autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc,monitoring,kvdb_postgres,kvdb_etcd')
web_1  | 2022-05-24 19:37:46.333 [INF] LOOPD: Starting liquidity manager
web_1  | 2022-05-24 19:37:46.334 [INF] LOOP: Wait for first block ntfn
web_1  | 2022-05-24 19:37:46.337 [INF] LOOP: Starting event loop at height
737756
web_1  | 2022-05-24 19:37:46.704 [INF] POOL: Auction server address:
pool.lightning.finance:12010
web_1  | 2022-05-24 19:37:46.707 [INF] CLDB: Checking for schema update:
latest_version=1, db_version=1
web_1  | 2022-05-24 19:37:46.708 [INF] RPCS: Starting trader server
web_1  | 2022-05-24 19:37:46.955 [INF] RPCS: Connected to lnd node dbnk
with pubkey
03d76e15709c57225560af75576b71c4d72dbac0dffaaba5ab8cc94e17ff8e708f
web_1  | 2022-05-24 19:37:46.985 [INF] ACCT: Watching spend of
20f2b81bc25d2b672acc00ff22b593c68718407acb329d3d5df29e7ef65ac85b:1 for
account 0365a0db0217ac0967309a41d0b8a921d1d9c540b4fc2cd3dbff9429765b23bf14
web_1  | 2022-05-24 19:37:47.794 [INF] AUCT: Successfully connected to
auction server
web_1  | 2022-05-24 19:37:48.031 [INF] AUCT: Shutting down auctioneer client
web_1  | 2022-05-24 19:37:48.032 [ERR] LITD: Could not start subservers:
unable to start account manager: unable to resume account
0365a0db0217ac0967309a41d0b8a921d1d9c540b4fc2cd3dbff9429765b23bf14: unable
to subscribe for account updates: checking pending batch failed: error
removing pending batch artifacts: error abandoning channels from previous
pending batch: error locating channel outpoint: no channel output found in
batch tx for matched order
933721491187fa827768e5ee4c750435ca1719ae5c8469b4de179a13495967d1
web_1  | 2022-05-24 19:37:48.032 [INF] LOOPD: Stopping gRPC server
web_1  | 2022-05-24 19:37:48.032 [INF] LOOPD: Liquidity manager stopped
web_1  | 2022-05-24 19:37:48.032 [INF] LOOP: Swap client terminating
web_1  | 2022-05-24 19:37:48.033 [INF] LOOP: Swap client terminated
web_1  | 2022-05-24 19:37:48.033 [INF] LOOPD: Swap client stopped
web_1  | 2022-05-24 19:37:48.033 [INF] LOOPD: Stopping REST server
web_1  | 2022-05-24 19:37:48.035 [ERR] ACCT: Unable to receive block
notification: rpc error: code = Canceled desc = grpc: the client connection
is closing
web_1  | 2022-05-24 19:37:48.035 [INF] LOOPD: Daemon exited
web_1  | 2022-05-24 19:37:48.035 [ERR] LNDC: Error closing lnd connection:
rpc error: code = Canceled desc = grpc: the client connection is closing
web_1  | 2022-05-24 19:37:48.036 [INF] SGNL: Received shutdown request.
web_1  | unable to start account manager: unable to resume account
0365a0db0217ac0967309a41d0b8a921d1d9c540b4fc2cd3dbff9429765b23bf14: unable
to subscribe for account updates: checking pending batch failed: error
removing pending batch artifacts: error abandoning channels from previous
pending batch: error locating channel outpoint: no channel output found in
batch tx for matched order
933721491187fa827768e5ee4c750435ca1719ae5c8469b4de179a13495967d1

*Diego Kolling*


Em ter., 24 de mai. de 2022 às 16:28, Diego Kolling ***@***.***>
escreveu:

**Comment by levmi** [comment] 2022-05-25 23:32
The CLI commands to recover the account:

`ssh umbrel@umbrel.local
cd ~/umbrel
./scripts/app stop lightning-terminal
cd ~/umbrel/app-data/lightning-terminal/data/.pool/mainnet
mv pool.db pool.db.bak
cd ~/umbrel
./scripts/app start lightning-terminal
docker exec -it lightning-terminal_web_1 bash
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts recover`

**Comment by jamaljsr** [comment] 2022-05-26 00:39
Here are the commands you should run on your umbrel to recover your account:
```sh
# connect to the Umbrel node
ssh umbrel@umbrel.local

# stop the Terminal app
cd ~/umbrel
./scripts/app stop lightning-terminal

# rename the pool db file
cd ~/umbrel/app-data/lightning-terminal/data/.pool/mainnet
mv pool.db pool.db.bak

# start the Terminal app
cd ~/umbrel
./scripts/app start lightning-terminal

# run bash in the LiT docker container
docker exec -it lightning-terminal_web_1 bash

# recover the account
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts recover
```

**Comment by diegokolling** [comment] 2022-05-26 02:07
Aand, I'm back! Thank you, guys! I have my Pool account with my full balance. So, to start ask orders again, what can I do to prevent what happened? What was the post mortem? Did our case triggered any update to Pool or LIghtning Terminal itself? Would it be recommended to use the web version instead? Thank you one more time!

**Comment by jamaljsr** [comment] 2022-05-26 02:44
Awesome! Glad you are back up and running. 

The problem appears to have been a connectivity issue during the process of creating a new batch. This was likely tor related. Due to this issue, your pool client was out of sync with your lnd node. Pool thought lnd had a pending channel open, but lnd didn't know anything about this channel. So when pool restarted, it attempted to cleanup this pending channel, but lnd threw an error because the pending channel didn't exist. This is what caused your restart loop.

It is unlikely that you've have this problem again, so you can proceed to create orders normally now. We've tracking the [issue](https://github.com/lightninglabs/pool/issues/365) in the pool repo to perform proper handling of this specific edge case if it were to happen to someone again in the future.

Thanks for providing all of that info. It was very helpful in identifying the cause of this issue.

**Closed by jamaljsr** 2022-05-26 02:44 UTC
Labels: bug

**Comment by diegokolling** [comment] 2022-05-26 13:10
You guys are amazing. Thank you one more time!

**Comment by diegokolling** [comment] 2022-07-11 13:12
Hey guys! So, here we go again, but now with a twist: I didnt have a unexpected restart or an energy blip. I suddenly lost access to my Lightning Terminal, Pool account and so on. Before going through the recovery process (as mentioned above) of my Pool account, where I happen to loose all my data of Pool orders, I would like to know from you:

Is it possible to recover my data afterwards? Like: maybe save my data -> recover account -> import data? How would that be?

2) Does updating to LND 15 and Umbrel 5 improve my chances of that not happening again?

Thank you guys one more time 🙏

@jamaljsr @levmi

**Comment by diegokolling** [comment] 2022-07-11 16:02
[umbrel-1657555338550-debug.log](https://github.com/lightninglabs/lightning-terminal/files/9085703/umbrel-1657555338550-debug.log)

As usual, my Umbrel logs.

**Comment by diegokolling** [comment] 2022-07-14 16:40
@levmi @jamaljsr  Im going to have to run through this process once again. Can I recover my Pool data afterwards?

**Comment by diegokolling** [comment] 2022-07-14 19:54
Here is my logs
[umbrel-1657828433534-debug.log](https://github.com/lightninglabs/lightning-terminal/files/9114917/umbrel-1657828433534-debug.log)

**Comment by guggero** [comment] 2022-07-15 07:53
There is no export/import yet. But if you still have the data, you can create a copy of the whole Pool data folder (not sure where that is located on an Umbrel, but it's the parent directory that contains the `pool.db` and `pool.macaroon` files, perhaps a search will find them).
If you then restore Umbrel and copy back that whole folder (most important are `pool.db` and `lsat.token`), you should get your account and all orders back (and you **do not** have to run account recovery!)

**Comment by diegokolling** [comment] 2022-07-15 12:17
Oh, very nice @guggero ! Thank you. Do you have a step by step guide to do that on Umbrel 5?

My Umbrel is running fine.

Doing that, will I be able to use Pool fully normally again? There are 12MM in Pool orders that I can’t see right now (+dozens of matched orders).

**Comment by diegokolling** [comment] 2022-07-15 13:50
No, no, it’s not an Umbrel problem, it’s a Pool problem and has been since the beginning. It’s the third time that I have to recover my Pool account, not any other app account or Umbrel account.

Umbrel recovery from seed was never an option, my Umbrel and Lightning node are working just fine.

@jamaljsr has a written a step by step guide, as you can see above, to recover my Pool account on Umbrel 4.18.

But since @levmi asked me to upgrade to Umbrel 5, it doesn’t work anymore.

So all I want is Jamal steps re-written for the new Umbrel ASAP, since I’m about a Week without access to my 12MM open orders on Pool and it’s starting to get really frustrating.

Sorry to be as frank and direct as I can, but I couldn’t find another way to put it.

**Comment by guggero** [comment] 2022-07-15 14:29
> I didnt have a unexpected restart or an energy blip. I suddenly lost access to my Lightning Terminal, Pool account and so on. Before going through the recovery process (as mentioned above) of my Pool account, where I happen to loose all my data of Pool orders, I would like to know from you:

Okay, I guess we've had a classic misunderstanding. Because you wrote you wanted to recover again, I didn't take a close look at the log file, so I didn't see what the cause was and assumed something went wrong with the Umbrel upgrade, they've been known to just delete data on upgrade. So I apologize for not reading more carefully. I look at dozens of issues every day, so things might slip by sometimes.

It looks like an attempted batch execution got stuck. This could be solved with a simple command, but not in the Umbrel environment (the setup is just too complicated). So you have three options:
1. Stop the `lightning-terminal` app, then send me the `pool.db` over [Slack](https://lightning.engineering/slack.html) (same username there, but I'll be traveling over the next few days and won't be responding immediately) for me to fix the state.
2. Run through the recovery process again, which means losing the orders and lease history. See the updated script below.
3. Wait for us to fix the bug that caused the error in the first place, then upgrade to the new version of LiT once we do.

I'm sorry this is such an inconvenience, but both LiT and Pool are still in alpha, so there are bugs to iron out.

In case you want to go with option 2, here's the **assumed** way to run things on Umbrel 5 (again, I have 0 experience with that system, this is purely guessing from what I found in their documentation):

```sh
# connect to the Umbrel node
ssh umbrel@umbrel.local

# stop the Terminal app
~/umbrel/scripts/app compose lightning-terminal stop

# rename the pool db file
cd ~/umbrel/app-data/lightning-terminal/data/.pool/mainnet
mv pool.db pool.db.bak

# start the Terminal app
~/umbrel/scripts/app compose lightning-terminal start

# run bash in the LiT docker container
~/umbrel/scripts/app compose lightning-terminal exec lightning-terminal bash

# recover the account
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts recover
```

**Comment by diegokolling** [comment] 2022-07-15 14:49
Oh, don't worry @guggero you've been doing really great, I'm really glad you are working hard on it and I appreciate that.

I've talked with Briscoe from Umbrel on the mean time and, looking at both set of commands, we've come to believe these one below are the better set (its a mix of Jamals and yours):

See what you think:

# connect to the Umbrel node
ssh [umbrel@umbrel.local](mailto:umbrel@umbrel.local)

# stop the Terminal app
cd ~/umbrel
./scripts/app stop lightning-terminal

# rename the pool db file
cd ~/umbrel/app-data/lightning-terminal/data/.pool/mainnet
mv pool.db pool.db.bak

# start the Terminal app
cd ~/umbrel
./scripts/app start lightning-terminal

# run bash in the LiT docker container
docker exec -it lightning-terminal_web_1 bash

# recover the account
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts recover

**Comment by guggero** [comment] 2022-07-15 15:56
Your account was involved in a batch about 15 days ago where two channels were sold, one for 0.7MM and one for 0.3MM, which explains the 1MM difference. You should see those two channels in your channel list.

The audit information is in the database you just removed/renamed. It also exists on the server side, but there currently is no option to "download" it again. Feel free to open a feature request issue in the Pool repo for that.

**Comment by diegokolling** [comment] 2022-07-15 16:45
Hmmm nice, I will. Meanwhile, is there a way for some of you guys to do it manually, if you don’t mind, please? I can wait, no problem. 

It will be important for me, tho, to keep track of my nodes return and Pool is an important part of it.

It’s the main part, actually! Since it accounts for more than 80% of my profits.

it’s been somewhere between 11-13 leasings, so no big deal I think. You’ve already spotted two. (Although I don’t know for how much they were opened for example).

**Comment by levmi** [comment] 2022-07-15 19:42
Hey Diego, currently, there isn't an easy way for us to grab that information for you. As Oli mentioned above, for the time being, the account recovery process does result in the database being removed/renamed. As mentioned, the option of pursuing the account recovery path means that the order and lease history were removed from the client. 

While I understand this might be frustrating, please take into account the alpha nature of both Pool and litd. That said, I'm really glad that Pool is driving a large portion of your revenue. We expect it to continue to grow. And, thank you for opening issues to improve this experience, the team is already discussing some of your ideas. As always, we will continue to work hard to improve the experience for all our users and we appreciate your feedback.

**Comment by diegokolling** [comment] 2022-07-15 21:35
Oh, great to hear from you Michael! Yah, Alpha software is kinda… well, it’s not that good sometimes.

But okay, than! Maybe someday I have everything back :) 

I liked the idea of posting suggestions and really enjoyed the early feedback. It’s great to see! 

Keep moving forward!

**Comment by em1xAdmin** [comment] 2023-04-10 03:10
Hi,
How can I perform an account recovery on a node running on Start9 Embassy?
I had an account setup with an ask offer about 2 weeks ago. Hadn't looked at it for a while and when I did I got the welcome banner with no evidence of my account,  Restore from my latest backup did not help.  There was no new updates installed.

**Comment by guggero** [comment] 2023-04-11 07:25
You should be able to follow this guide: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery
Maybe you also need to move/rename the `pool.db` as described in the step above.

Some arguments/flags might change on Start9 Embassy, unfortunately I'm not familiar with software and can't give you more info on that. Their support might be able to help you.
