### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by QueenGit** [lightninglabs/lightning-terminal#204] opened 2021-03-10 14:30 UTC
Hey there.
I update from an older version to the v0.4.1-alpha.
If I start the litd I get the following output on:

> 2021-03-10 15:24:34.531 [INF] LITD: Dialing lnd gRPC server at localhost:10009
> 2021-03-10 15:24:34.715 [INF] LITD: Listening for http_tls on: [::]:3050
> 2021-03-10 15:24:34.719 [INF] SGNL: Received shutdown request.
> error displaying startup info: error querying remote node : rpc error: code = Unknown desc = expected 1 macaroon, got 0

The node is hosting on the same machine.

Don' know what is wrong. What can I do to fix it?

**Comment by guggero** [comment] 2021-03-10 14:39
Duplicate of https://github.com/lightninglabs/lightning-terminal/issues/195.

You need to specify `remote.lnd.macaroonpath=~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon` in your config. This bug will be fixed in the next version.

**Closed by guggero** 2021-03-10 14:39 UTC
