### ISSUE TITLE
I can´t acces to the app in Umbrel

### ISSUE THREAD

**Issue by tombatossal** [lightninglabs/lightning-terminal#411] opened 2022-08-25 10:11 UTC
When I launch the app this message appear in the screen:
Oops, there was an error
There was an error connecting to Lightning Terminal. Error code: EHOSTUNREACH

I thought I could unistall the app end re-insyall, but I don´t find the way

Thanks in advance, best regards

**Comment by ellemouton** [comment] 2022-08-25 10:18
Hi @tombatossal , I think this issue may be on the Umbrel side. Have you asked for help there?

**Comment by tombatossal** [comment] 2022-08-25 10:19
Not yet, I´m going , anyway thanks

**Comment by ellemouton** [comment] 2022-08-25 10:22
ok cool, Im going to close this issue in the meantime. Feel free to re-open it if you discover that the issue is in-fact on the Litd side. Thanks and good luck!

**Closed by ellemouton** 2022-08-25 10:22 UTC
