### ISSUE TITLE
Terminal Web counts Loop In as Profit

### ISSUE THREAD

**Issue by eliotcougar** [lightninglabs/lightning-terminal#614] opened 2023-08-03 07:31 UTC
After performing a Loop In, the Terminal Web summary shows obviously wrong data. CSV export table also shows the Looped In amount in the Fee column. It appeared as profit only after the swap server swiped the funds from the address yesterday…
![image](https://github.com/lightninglabs/lightning-terminal/assets/1861169/b64ae1de-3157-47d9-a992-f4b5db2ee162)

7/26/2023, 11:20:35 AM | **1899024** | Loop In 1,900,000 sats (swap server) | swap_id=06ddda4c1d2658813739d7f6b00945114faa389ea947edb4da3ed72b946c6fba

Swap address: bc1ptrz6ktle0uk56eq2v3jv9yhq6a6sdr2tdg6ta4d0vfjqswmjkhvqcy6vpp

**Expected behavior**

Loop In shouldn't be counted as profit.

**To reproduce**

Do a Loop In, wait for it to complete.

**System information**
litd 0.10.4, with external LND on Windows 10...

**Comment by levmi** [comment] 2023-08-03 14:33
Thanks for the report Eliot! Looking into this on our end, will let you know if we need more details.

**Comment by jamaljsr** [comment] 2023-08-04 19:54
I have tried to reproduce this and was not able to. I tested on regtest and testnet and the fees were calculated correctly.

Since the fee is pulled directly from `loopd`, can you check the CLI output of `loop listswaps` for this swap to see what value is returned for `cost_server`?

**Comment by eliotcougar** [comment] 2023-08-05 08:30
> Since the fee is pulled directly from `loopd`, can you check the CLI output of `loop listswaps` for this swap to see what value is returned for `cost_server`?
`cost_server` for that swap shows as `-1899024`…

**Comment by jamaljsr** [comment] 2023-08-05 15:54
Ah ok, that explains where this value is coming from in the UI. I'm not sure if this is related to taproot swaps but that may be a hint. I'll ping the Loop team to see if someone can assist further.

**Comment by levmi** [comment] 2023-08-11 12:46
Hey Eliot, really appreciate the feedback here. We're going to work on getting a fix in for this over the course of the next week or so. Just wanted to let you know that we ack the issue and are prioing a fix, but that's the timeline that we're looking at so that you have full vis and know what to expect next :)

**Comment by levmi** [comment] 2024-07-31 16:25
I believe this was fixed on the Loop backend via the following changes. https://github.com/lightninglabs/loop/pull/751
https://github.com/lightninglabs/loop/pull/764 But, let me know if you're still seeing it.

**Closed by levmi** 2024-07-31 16:25 UTC
Labels: bug
