### ISSUE TITLE
Stuck in Initiated

### ISSUE THREAD

**Issue by mlewk** [lightninglabs/lightning-terminal#200] opened 2021-03-08 03:05 UTC
I have started a Loop Out and it is stuck in initiated for over 12 hours. How do I fix it? I am using the User Interface.
![image](https://user-images.githubusercontent.com/30084414/110269140-0ec97000-7f91-11eb-89f5-b84e777513d4.png)

**Comment by guggero** [comment] 2021-03-08 08:49
Can you post any more details of the swap please? The swap hash and the logs?

**Comment by mlewk** [comment] 2021-03-08 13:03
I am using the User Interface, how do I access the swap hash and the logs? Thanks

**Comment by guggero** [comment] 2021-03-08 14:49
If you're using Umbrel, you might need to ask their support where the LiT data directory is located.
If you're using LiT standalone, look in `~/.loop/logs`

**Comment by mlewk** [comment] 2021-03-08 14:59
ok I found `~/.loop/logs` What info do you need?

**Comment by guggero** [comment] 2021-03-08 15:42
The whole log is probably the easiest.

**Comment by mlewk** [comment] 2021-03-08 15:44
All I see is `mainnet` in the logs folder

**Comment by guggero** [comment] 2021-03-08 15:48
No file inside?

**Comment by mlewk** [comment] 2021-03-08 15:51
in `/home/umbrel/umbrel/app-data/lightning-terminal/data/.loop/logs` all i see is `mainnet`

**Comment by guggero** [comment] 2021-03-08 16:15
Yes, inside `mainnet` is there a log file?

**Comment by mlewk** [comment] 2021-03-08 16:16
I do not see any files inside the `mainnet` folder.

**Comment by guggero** [comment] 2021-03-08 16:21
Okay, then check `/home/umbrel/umbrel/app-data/lightning-terminal/data/` if there is a `lit.log` anywhere in any of the sub directories.

**Comment by mlewk** [comment] 2021-03-08 16:42
I found `litd.log` file in `/home/umbrel/umbrel/app-data/lightning-terminal/data/.lit/logs/mainnet`. Is that correct?

**Comment by guggero** [comment] 2021-03-08 16:43
yes

**Comment by mlewk** [comment] 2021-03-08 16:45
what is the easiest way to export the file from my pi to my windows desktop?

**Comment by mlewk** [comment] 2021-03-08 17:39
[litd.log](https://github.com/lightninglabs/lightning-terminal/files/6103144/litd.log)

**Comment by guggero** [comment] 2021-03-09 09:24
I see `f99673 Server update: FAILED_OFF_CHAIN_TIMEOUT received, timestamp: 2021-03-07 16:15:25.601380392 +0000 UTC` in the log.
Was it the swap over 0.3 BTC that you saw was stuck? It should've gone to a failed state now. Large amount sometimes just take a while.

**Comment by mlewk** [comment] 2021-03-09 13:45
Yes, that is the swap. Should I just re do the swap since it failed? Or should I wait because it still says initiated but not failed?

**Comment by mlewk** [comment] 2021-03-09 14:16
I have refreshed the page and it still shows as Initiated.
![image](https://user-images.githubusercontent.com/30084414/110483785-0ddf2e00-80b8-11eb-93b5-02d6728c586a.png)

**Comment by mlewk** [comment] 2021-03-10 01:43
It still says Initiated. Is there a way to cancel it and perhaps to a loop for a smaller amount?

**Comment by guggero** [comment] 2021-03-10 08:35
Have you tried restarting LiT and/or Umbrel?

**Comment by mlewk** [comment] 2021-03-10 14:26
I restarted everything now it says terminated so it seems to have recognized it failed.

**Comment by guggero** [comment] 2021-03-10 14:45
Okay, thank you for confirming that. I've created an issue in the correct repo https://github.com/lightninglabs/loop/issues/354.

Closing this since it's not directly related to the UI.

**Closed by guggero** 2021-03-10 14:45 UTC

**Comment by guggero** [comment] 2021-03-11 09:26
@mlewk We're trying to reproduce the issue of the UI not updating the state. It would be helpful to get the log from when you restarted Umbrel. Could you please upload the whole `litd.log` again? Thank you!

**Comment by mlewk** [comment] 2021-03-11 14:11
[litd.log](https://github.com/lightninglabs/lightning-terminal/files/6123518/litd.log)
