### ISSUE TITLE
Cannot start litd after it crashes

### ISSUE THREAD

**Issue by kccheung** [lightninglabs/lightning-terminal#154] opened 2020-11-24 03:46 UTC
Version of litd I am using: 0.3.0-alpha

Debug log:

> 2020-11-24 11:36:52.750 [INF] AUCT: Successfully connected to auction server
> 2020-11-24 11:36:52.937 [INF] AUCT: Shutting down auctioneer client
> 2020-11-24 11:36:52.938 [ERR] LITD: Could not start subservers: unable to start account manager: unable to resume account XXX: unable to subscribe for account updates: EOF
> 2020-11-24 11:36:52.939 [INF] LOOP: Swap client terminating
> 2020-11-24 11:36:52.939 [INF] LOOP: Swap client terminated
> 2020-11-24 11:36:52.939 [ERR] ACCT: Unable to receive block notification: rpc error: code = Unavailable desc = transport is closing
> 2020-11-24 11:36:52.940 [ERR] LNDC: Error closing client connection: rpc error: code = Canceled desc = grpc: the client connection is closing
> 2020-11-24 11:36:52.940 [INF] SGNL: Received shutdown request.
> 2020-11-24 11:36:52.940 [INF] SGNL: Shutting down...
> 2020-11-24 11:36:52.940 [INF] SGNL: Gracefully shutting down.
> 2020-11-24 11:36:52.940 [ERR] ACCT: Unable to determine spend for account XXX: rpc error: code = Unavailable desc = transport is closing
>

**Comment by guggero** [comment] 2020-11-24 08:09
Possible duplicate of https://github.com/lightninglabs/pool/issues/176.

Can you please update to the latest version of LiT and try again?
If the issue persists, do you see the same error as mentioned in the linked issue?
If not, can you give some more details, for example if you're running in integrated or remote node mode?
And the logs of the error on startup.

**Comment by guggero** [comment] 2020-12-14 08:23
Closing due to inactivity. Assuming that updating to the latest version fixed the problem.

**Closed by guggero** 2020-12-14 08:23 UTC
