### ISSUE TITLE
Crash due to concurrent write to websocket connection

### ISSUE THREAD

**Issue by lukaszsamson** [lightninglabs/lightning-terminal#206] opened 2021-03-21 06:57 UTC
While having litd running in the background and a web browser tab open on `https://localhost:8443/loop` on my local machine

**Expected behavior**

No crash

**Actual behavior**

```
2021-03-21 06:52:55.446 [INF] RPCS: Received new block notification: height=675573
2021-03-21 07:00:57.505 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/BatchSnapshots
2021-03-21 07:00:57.728 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/NextBatchInfo
2021-03-21 07:10:57.489 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/BatchSnapshots
2021-03-21 07:10:57.862 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/NextBatchInfo
panic: concurrent write to websocket connection

goroutine 641 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc002707f00, 0x31f0b01, 0x31f0bf0, 0x0, 0x0, 0x47b0f196e50f3, 0xc002707f08)
	github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x62e
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00055d080, 0x9, 0x31f0bf0, 0x0, 0x0, 0x1, 0x0)
	github.com/gorilla/websocket@v1.4.2/conn.go:763 +0x249
github.com/improbable-eng/grpc-web/go/grpcweb.(*webSocketResponseWriter).ping(0xc002db9230, 0xc001383200)
	github.com/improbable-eng/grpc-web@v0.12.0/go/grpcweb/websocket_wrapper.go:60 +0xb1
created by github.com/improbable-eng/grpc-web/go/grpcweb.(*webSocketResponseWriter).enablePing
	github.com/improbable-eng/grpc-web@v0.12.0/go/grpcweb/websocket_wrapper.go:46 +0xea
```
**To reproduce**

Not sure

**System information**

Standalone app

lnd: remote
other: integrated

v0.4.1-alpha from github releases

MacBook Pro 2016

macOS 10.15.7

**Comment by guggero** [comment] 2021-03-22 10:01
I'm unable to reproduce this locally. Do you remember what you were doing at the time of the crash? Was the browser tab just sitting there idly? Or did you have multiple tabs with LiT open?

**Comment by lukaszsamson** [comment] 2021-03-22 11:41
I had one tab open sitting idly in the background.

**Comment by jamaljsr** [comment] 2021-07-16 02:08
Closing this since we were unable to reproduce the issue. @lukaszsamson please feel free to reply here if you are still facing this issue.

**Closed by jamaljsr** 2021-07-16 02:08 UTC
Labels: bug
