### ISSUE TITLE
Error: Unable to perform Loop Out

### ISSUE THREAD

**Issue by beeforbacon** [lightninglabs/lightning-terminal#92] opened 2020-08-05 00:37 UTC
When in Lightning-Terminal, performing loop out with automatic channel selection with any amount of sats gives the following error:

```
Unable to perform Loop Out
2: cannot initiate swap: rpc error: code = OutOfRange desc = amount above current maximum
```

What is the current maximum per the error? Thank you. 
![unableloopout](https://user-images.githubusercontent.com/51864803/89358800-2518f180-d679-11ea-9754-2b67dbd35c96.PNG)

**Comment by jamaljsr** [comment] 2020-08-05 01:58
Hey @beeforbacon this is actually a temporary error caused by the backend loop server. It'll usually be resolved if you try again a little later. Can you check now to see if it'll work?

**Comment by beeforbacon** [comment] 2020-08-05 02:55
> 
> 
> Hey @beeforbacon this is actually a temporary error caused by the backend loop server. It'll usually be resolved if you try again a little later. Can you check now to see if it'll work?

Just tried with as low as 3 mil sats. same error, unfortunately.

**Comment by jamaljsr** [comment] 2020-08-06 16:10
Are you still facing this issue? If so, can you provide a snippet of your `lnd.log` file when the swap is initiated until the error is produced?

**Comment by carlaKC** [comment] 2020-08-13 16:47
This was a temporary error on server side, which should have been resolved now. 

Did you come right @beeforbacon ?

**Comment by jamaljsr** [comment] 2020-09-02 19:27
@beeforbacon I am going to close this issue out for now. Please let us know if you continue to face the problem.

**Closed by jamaljsr** 2020-09-02 19:27 UTC
